### ISSUE TITLE
Plugin not loading on Velocity

### ISSUE THREAD

**Issue by VictorGamer15** [LielAmar/2FA#117]
**Describe the bug**

2FA version 1.6.3 can't load on Velocity. Also, velocity-plugin.json doesn't exist inside the plugin.

**How To Reproduce**

**Expected behavior**

The plugin should load correctly.

**Screenshots and Videos**

![imagen](https://user-images.githubusercontent.com/69861104/187506437-983c66ef-2b80-40a1-b011-21e5086610fb.png)

**Server Information**

 - OS: Ubuntu 20.04
 - Java Version: 17

**Additional context**

Older versions of 2FA, have the velocity-plugin.json file inside.

**Comment by Enoughsdv** [comment]
The plugin does not support Velocity.

**Comment by VictorGamer15** [comment]
Then you should remove the part in the plugin's description and spigot page, that has support for Velocity.
![imagen](https://user-images.githubusercontent.com/69861104/188283932-57d7e583-28f4-4edd-aff5-e7a9293311db.png)
![imagen](https://user-images.githubusercontent.com/69861104/188283940-e924fa60-07d1-42bf-a06d-31f6aad47afd.png)

**Comment by Enoughsdv** [comment]
Right, maybe you forgot to add "velocity-plugin.json" inside the project, feel free to create a PR adding this and obviously tested and it works :)

**Comment by VictorGamer15** [comment]
Ok, I tried adding the old velocity-plugin.json, and it worked. I already tried to install 2FA in my backend servers and it works perfectly. I'll create a pull request right now.
