### ISSUE TITLE
Is the Lielamar repo offline?

### ISSUE THREAD

**Issue by gersomonline** [LielAmar/2FA#138]
**Describe the bug**
When trying to build 2FA, Gradle can't download certain dependencies because it can't connect to the Lielamar repo. Is it offline?

**How To Reproduce**
Try to build 2FA without the libraries downloaded.

**Expected behavior**
Every artifact resolves successfully.

**Screenshots and Videos**
N/A

**Server Information**
N/A

**Additional context**
I found a alternative repository for the ``libby`` library: https://repo.alessiodp.com/#/releases/, when adding that locally it works. Also for the LielsUtils you can consider adding it as a jar file in a libs directory instead.

**Comment by DirtyConcept** [comment]
It is offline, the new version will be compiled with all the utils from it in the plugins' files
