### ISSUE TITLE
Registration 2fa Code incorrect

### ISSUE THREAD

**Issue by LoneDevilX** [LielAmar/2FA#143]
**Describe the bug**

**How To Reproduce**

**Expected behavior**

2fa should be recorded and entering code should done set up

**Screenshots and Videos**

![image](https://github.com/LielAmar/2FA/assets/67851836/e45910ba-5cbb-419f-baf5-f285993ac046)

**Server Information**

 - OS: [e.g. Ubuntu 18, CentOS 7]
 - Java Version: Java18
 - Server Game Version: 1.19.4
 - Plugin Version: 1.6.3
 - Plugin List: -
 - Using Bungeecord? No
 - Loaded Bungeecord? No

**Additional context**

**Comment by DirtyConcept** [comment]
Fixed in 1.7.0
