### ISSUE TITLE
Map overflow

### ISSUE THREAD

**Issue by InstantlyMoist** [LielAmar/2FA#25]
https://github.com/LielAmar/2FA/blob/4af01dbbac266e681619ec0eb1538a671d155dfe/src/main/java/com/lielamar/auth/bukkit/handlers/AuthHandler.java#L272

This will create a new map every single time someone sets up 2FA. This will (very unlikely) cause the maps to overflow as there is a 16 bit integer limit on the maps. This can be fixed by 'reserving' a few maps for your plugin and reusing the later.

**Comment by LielAmar** [comment]
Correct, did not think of that.
I will implement your suggestion as soon as possible and keep the issue open until then :)

**Comment by LielAmar** [comment]
Fixed.
Thank you for letting me know :)
