### ISSUE TITLE
"Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!"

### ISSUE THREAD

**Issue by janilowski** [LielAmar/2FA#30]
Good morning,
The plugin is working fine in practically every aspect. However, I noticed a message appearing in the console every time I start my server:
<img width="936" alt="Screenshot 2021-02-13 at 2 04 46 PM" src="https://user-images.githubusercontent.com/76809077/107850745-01431f00-6e05-11eb-8dd6-566b91391cfc.png">

Steps to replicate:

1. Have 2FA installed on your Paper server
2. Start the server
3. Look at the console
4. The message should appear every time you start your server

I'm using 2FA version 1.1.8
Here is my config.yml: https://pastebin.com/uD9jPpAu
I'm running my server on Paper 1.16.5 (build 468)
My plugin list:
<img width="308" alt="Screenshot 2021-02-13 at 2 12 25 PM" src="https://user-images.githubusercontent.com/76809077/107850798-829ab180-6e05-11eb-9069-07946278bc5b.png">

**Comment by LielAmar** [comment]
The plugin is developed for versions before 1.13. I don't specify an api-version to support multiple.
This warning shouldn't be a problem at all! :)
