### ISSUE TITLE
Translatable main menu

### ISSUE THREAD

**Issue by SirKappa** [LielAmar/2FA#32]
https://i.imgur.com/pvARxIM.png
Dear developer, I already wrote about this problem, could you add the ability to translate the main menu? More precisely, its customization.

**Comment by LielAmar** [comment]
Thank you for the suggestion. I will probably add this in the next version!
Anything else? :)

**Comment by SirKappa** [comment]
> Thank you for the suggestion. I will probably add this in the next version!
> Anything else? :)

The plugin is very good, I don't even know what else to add. Thanks for developing it.

**Comment by LielAmar** [comment]
Done :)
