### ISSUE TITLE
Invalid messages

### ISSUE THREAD

**Issue by ImFoxxy** [LielAmar/2FA#34]
My server is displaying the incorrect message on auth. It's saying that that code is invalid, however it appears that it's authing the user.

**Comment by LielAmar** [comment]
Hi Foxxy, can you provide a deeper explanation and possibly a video of what's happening? :)

**Comment by ImFoxxy** [comment]
Sure; here is a video
https://www.youtube.com/watch?v=yKOiEQeZrFM

**Comment by LielAmar** [comment]
Do you get any errors or something like that? Can you replace your messages.yml with the default one and see if it happens?

Also, just for some information, are you using bukkit, spigot or paper? what version? what is the plugin version? :)

**Comment by ImFoxxy** [comment]
I have no errors, I have the plugin running on both Spigot and BungeeCord; I have tried this and it's the same thing happening.

1.8.9 spigot/paper and latest bungeecord. Latest plugin version

**Comment by LielAmar** [comment]
do you mind joining my discord server and creating a ticket so we can easily check what's causing it?
https://discord.gg/sKPAJ89c
