### ISSUE TITLE
MySQL automatic reconnect / connect

### ISSUE THREAD

**Issue by Tiippex** [LielAmar/2FA#35]
Hello,

I have a problem using mysql. I have a few servers with less traffic so the mysql connection closes after a while. When I join I get the following exception and can't authenticate myself:

![image](https://user-images.githubusercontent.com/16509128/118474266-2ea4af00-b70b-11eb-9ce0-e38281c1dcec.png)

2FA is able to create the connection after relogging in. Could you add the "autoReconnect=true" connection thingy?

Tiippex

**Comment by LielAmar** [comment]
Fixed :)

**Comment by Tiippex** [comment]
Wow that was fast. Thank you very much!
