### ISSUE TITLE
2fa enable error

### ISSUE THREAD

**Issue by ods-im** [LielAmar/2FA#39]
Jdk 16
server version paper1.17
server log    https://pastebin.com/aPABhznt

Plugins (36): 2FA*, AdvancedAchievements, AdvancedNMotd, Citizens, CMI, CMILib, CoreProtect, DungeonsXL, FastAsyncWorldEdit (WorldEdit), Gunging_Ootilities_Plugin, HeadDatabase, HoloDropsX, ItemsXL, LangUtils, LiteSignIn, LuckPerms, MMOCore, MMOItem_Shrubs, MMOItems, Multiverse-Core, MythicLib, NoOneFishing, Oraxen, PlaceholderAPI, PlayerPoints, PlayerVaults, PlugMan, ProtocolLib, PvPManager, Residence, SmoothTimber, TAB, Vault, VentureChat, WorldEdit, WorldEditSelectionVisualizer

**Comment by ods-im** [comment]
Enter 2fa enable
There is no response in the game, there will be an error in the log in the background, and after that enter ever 2fa command there will prompt code error .

**Comment by ods-im** [comment]
command

**Comment by LielAmar** [comment]
Thank you for contacting me!
I'll go over the error in the following days :)

**Comment by LielAmar** [comment]
Hi ods-im,
I've added a message to let players know when the plugin is generating the 2FA.
Depending on your machine, the time it takes to generate the 2FA key & QR code varies.

The error you provided should, however, be fixed through some code improvements :)
