### ISSUE TITLE
MySQL and autoReconnect=True

### ISSUE THREAD

**Issue by Mirko045** [LielAmar/2FA#40]
The autoReconnect=true doesn't seem to fix the problem caused by wait_timeout completely.

This seems to be a known problem with the autoReonnect flag as seen [here](https://stackoverflow.com/a/667334).
The query that triggers the reconnect will still be "rejected" and cause the player to not appear to have 2FA set-up, which I can confirm with my ingame experience.
The first log-in after the wait_timeout period has been reached provides me with a new QR-Map to setup 2FA, if I relog instead of setting up 2FA again, I won't be given a map and just asked for my code, which is expected behaviour.

Additional Information:
MySQL is a MariaDB 10.3.27 under a Debian 10 system. 
Plugin version used is 1.3.4.
Related log to when this error is experienced can be found [here](https://pastebin.com/NXXDk387)
Edit: Server Jar used is a Purpur, which is a performance fork of PaperMC.

Potential fix:
Maybe let the connection handler send a package every x-hours when MySQL is enabled to prevent the wait_timeout to be reached?

**Comment by LielAmar** [comment]
I've been getting multiple reports everytime I publish a new version with a potential fix.

Your solution sounds good though. I believe I can implement it in the next couple of days :)

**Comment by LielAmar** [comment]
Fixed!
The plugin will now use HikariCP's connection pool to manage SQL databases.
