### ISSUE TITLE
InaccessibleObjectException on 1.17.1

### ISSUE THREAD

**Issue by iGabyTM** [LielAmar/2FA#43]
https://paste.helpch.at/evexiquyuk.hs

**Comment by LielAmar** [comment]
Hey iGabyTM!
Are you using Java 16?

**Comment by iGabyTM** [comment]
Yeah

**Comment by LielAmar** [comment]
That's because I've changed the way the plugin handles dependencies.
I'm still looking into a solution, but Java 16 does not support the current dependency manager.
I will, however, add a temporary solution to make the plugin still run, but some key features might not work.

**Comment by LielAmar** [comment]
I forgot to mention that you can add those parameters to your run script and it'll also fix the problem for java 16:
`--add-opens java.base/java.net=ALL-UNNAMED`

**Comment by LielAmar** [comment]
Should be fixed now for Spigot 1.16.5 and above.
If you are using Java 16 with any other version of Minecraft, you'd have to add the `--add-opens java.base/java.lang=ALL-UNNAMED` flag :)
