### ISSUE TITLE
Suggestion: prevent chat at proxy level with a bungee plugin

### ISSUE THREAD

**Issue by GovindasOM** [LielAmar/2FA#47]
Prevent chat at proxy level with a bungee plugin if the player has not been validated with 2FA. This would help to make the plugin more useful, as currently there is decent amount of things a non-validated user can still do (for example Skript's effect commands still work)

**Comment by LielAmar** [comment]
This should already be a feature.
Did you install the plugin on your Proxy as well? if so, did commands were still executed?

**Comment by GovindasOM** [comment]
yes it is on bungee, the / commands do not get executed, but ! commands (provided by Skript) still get executed, so ideally it'd be prevented with full chat prevention that wouldn't look only for / symbol

**Comment by LielAmar** [comment]
Fixed on next version (1.4.2)
