### ISSUE TITLE
Suggestion: make getting secret easier

### ISSUE THREAD

**Issue by GovindasOM** [LielAmar/2FA#48]
Currently the only way to get secret is scan QR code or find it inside google.com URL (complicated due to URL formatting). It'd be nice to have a way to view the secret easily, maybe upon hover of a message. (I prefer entering secrets manually instead of scanning QR codes) 

Almost every website that uses TOTP has this feature.

**Comment by LielAmar** [comment]
Added in next release (1.4.2)
