### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by Corrupteddroid** [LielAmar/2FA#54]
[Suggestions]

Allow Us To Set Players 2Fa Service Keys 
So The Owner Has Control Of Changing Of There Service Keys And If There Service Keys Lost We The Owners Can Change It In The Config Or Something

[Also Please Not Just A Command Because I Want To Set A 100 Character Service keys For Admins]

**Comment by LielAmar** [comment]
I must recommend against setting the 2FA keys manually, but if you want to do that, you can directly edit the database.
A command would be pointless since it can cause many many problems.

**Comment by ods-im** [comment]
服务器地址可以用微软的吗？我找不到微软的服务器地址。谷歌的我连接不上，被墙

**Comment by LielAmar** [comment]
> 服务器地址可以用微软的吗？我找不到微软的服务器地址。谷歌的我连接不上，被墙

Switching to a different provider, like Microsoft, is possible as long as they do have this serivce.

**Comment by LielAmar** [comment]
Closing for irrelevance
