### ISSUE TITLE
[Idea for better Security] Encrypt TOTP keys

### ISSUE THREAD

**Issue by StormyIceLeopard** [LielAmar/2FA#62]
You encrypt the IP addresses but not the TOTP keys?
You really should encrypt the TOTP keys.

General rule of thumb for TOTP/API Keys:
The app you use to generate the 6 digits should give the keys back (such as Authenticator).
Not the service where the key came from (such as this plugin, SendGrid.com API keys).

**Comment by LielAmar** [comment]
No worries at all! Thank you for the suggestions anyways, it's always nice getting them! :)
