### ISSUE TITLE
Disable Click to Open QR message?

### ISSUE THREAD

**Issue by StormyIceLeopard** [LielAmar/2FA#66]
I use a local custom QR generator that is not accessable to the outside world, yes I am that parenoid.
I am wondering how to disable the Click to Open QR url message altogether.

**Comment by LielAmar** [comment]
Hey!
The "Click to open QR" message specifically is using a different system than the rest of the messages, so you can't disable it iirc.

You can try setting this message to an empty string I messages.yml, and if it doesn't work lmk and I'll add it in the next release :)

**Comment by GersomR-afk** [comment]
Fixed and merged, will be added in the next release.

**Comment by LielAmar** [comment]
Version 1.6.0 is out with a fix to this issue!

Thanks to GersomR-afk for the fix to this bug.
