### ISSUE TITLE
A map with a QR code may drop.

### ISSUE THREAD

**Issue by ToxaEagle123** [LielAmar/2FA#75]
If a player receives a map with a QR code through the "/2fa enable" command and then this player dies, then the map may drop and other players can receive this map in this way.

I think it would be nice to prevent this.

**Comment by GersomR-afk** [comment]
Is implemented and merged will be added in the next release.

**Comment by LielAmar** [comment]
Version 1.6.0 is out with a fix to this issue!

Thanks to GersomR-afk for the fix to this bug.
