### ISSUE TITLE
[Great idea] fail-2fa-execution

### ISSUE THREAD

**Issue by msmanui** [LielAmar/2FA#81]
Hey! I really like your plugin, works great! 

Could be possible, you could add fail-commands?
For example if a player execute the 2fa 10 times wrong,  it would ban?  (Once the player already has the 2fa enabled)

**Comment by LielAmar** [comment]
Hey msmanui!
That's possible to do with the API.
I might do that myself if I have some free time in the next few days, but there's a pretty good explanation on how to do that (here)[https://github.com/LielAmar/2FA/wiki/Using-the-API#spigot-examples]

**Comment by LielAmar** [comment]
Can be done with the API.

Closed.
