### ISSUE TITLE
communication method

### ISSUE THREAD

**Issue by ecnebbence** [LielAmar/2FA#94]
The plugin keeps spamming this message in the chat, but the communication method is set up correctly.
![javaw_MfYR3uEicG](https://user-images.githubusercontent.com/43892363/177033245-8c59b8fe-e3fe-4774-93c3-c51214ff87c1.png)
![WindowsTerminal_7AyooLP9hO](https://user-images.githubusercontent.com/43892363/177033273-b82b8b38-4c85-4004-9a7f-4a7e7480ab8a.png)
I'm using the latest release on bungeecord and I'm getting the issue on server version 1.16.5-1.18.

**Comment by Enoughsdv** [comment]
Hi, can you send the log of what comes out when you put /2fa report?

**Comment by ecnebbence** [comment]
Server Java and OS
- Java Runtime Version: 16.0.2+7
- OS: Linux

Server Plugins
- VoidGenerator | 1.0 | Enabled: true
- ImageOnMap | 4.2.2 | Enabled: true
- JoinFullServer | 1.0 | Enabled: true
- PlaceholderAPI | 2.11.1 | Enabled: true
- PlugMan | 2.1.7 | Enabled: true
- ViaVersion | 4.3.1 | Enabled: true
- HolographicDisplays | 2.4.9 | Enabled: true
- ViaBackwards | 4.3.0 | Enabled: true
- Playtimes | 1.3.10 | Enabled: true
- LuckPerms | 5.3.42 | Enabled: true
- PlasmoVoice | 1.0.10 | Enabled: true
- 2FA | 1.6.2 | Enabled: true
- ServerSelectorX | 3.6.3 | Enabled: true
- Vault | 1.7.3-b131 | Enabled: true
- Multiverse-Core | 4.2.2-b812 | Enabled: true
- WorldEdit | 7.2.10+1742f98 | Enabled: true
- MysqlEcoBridge | 3.4.1 | Enabled: true
- Essentials | 2.19.4 | Enabled: true
- EssentialsChat | 2.19.4 | Enabled: true
- EssentialsSpawn | 2.19.4 | Enabled: true
- SimplePortals | 1.6.7 | Enabled: true
- TabList | 5.6.0 | Enabled: true

Server Jar, Versions and Information
- Spigot Build version: git-Paper-794 (MC: 1.16.5)
- Server Version: 1.16.5-R0.1-SNAPSHOT
- Version Instance: v1_16_5
- NMSVersion Instance: v1_16_R3
- Max Memory: 2147 MB
- Free Memory: 769 MB
- Total Memory: 2147 MB

Communication Method & Proxies:
- Using Bungeecord: true
- Is Proxy Loaded: true
- Communication Method in config: PROXY
- Communication Timeout in config: 30 ticks

Attach this file when creating an issue on GitHub: https://github.com/LielAmar/2FA/issues
You can also join our discord server and talk to us there: https://discord.com/invite/NzgBrqR

**Comment by leSs-cOws** [comment]
I fixed this by writing proxy instead of PROXY. See if that might fix it? After that maybe try to use a mongodb database. I am using one currently to store the plugin's data.

**Comment by DirtyConcept** [comment]
This issue should not be happening in release 1.7.0, if this problem happens I'll reopen this issue
