### ISSUE TITLE
Chat messages are sent even if chat event is disabled

### ISSUE THREAD

**Issue by Chiruso** [LielAmar/2FA#95]
**Describe the bug**

**How To Reproduce**

**Expected behavior**

The message shouldn't be sent
**Screenshots and Videos**

![image](https://user-images.githubusercontent.com/70108545/179331586-fc5e822b-7c46-4db0-95fc-d93331b2f59b.png)

**Server Information**

 - OS: Ubuntu 18
 - Java Version: Java Runtime Version: 17.0.1+12-LTS-39
 - Server Game Version: 1.18.2
 - Plugin Version: 1.6.2
 - Using Bungeecord? Yes (just waterfall, limbo & survival server)
 - Loaded Bungeecord? No

**Additional context**

I'm using ChatControlRed 10.12.4

**Comment by Enoughsdv** [comment]
Hi, can you send the log of what comes out when you put /2fa report?

**Comment by Chiruso** [comment]
Sure,
[https://pastebin.com/ZG6jDjqh](https://pastebin.com/ZG6jDjqh)

**Comment by Enoughsdv** [comment]
If you are using Bungeecord, please put the plugin inside the Bungeecord plugins folder and in the "communication-method" setting instead of NONE put PROXY.

**Comment by LielAmar** [comment]
@Enoughsdv pointed out the solution to the problem.
As you can see, in the link you've provided, ` Is Proxy Loaded: false` means the proxy couldn't load the plugin.
This happens when you don't have the 2fa.jar inside your proxy's plugins folder.

Closed.
