### ISSUE TITLE
2FA Google Auth Issue

### ISSUE THREAD

**Issue by fortunatas1** [LielAmar/2FA#99]
Hello, I installed 2FA and everything worked for a couple of weeks. Now when entering the code, it says that it is incorrect. It works if you write it when a new code is updated.
Trying to re-enable 2FA still doesn't work.
Only after recording everything was fine for a few weeks, then the problems started. Had to wait for 1 code to go through and enter the old one, now it takes about 1.5 laps (password) to log in.

Server Java and OS
- Java Runtime Version: 17.0.1+12-LTS-39
- OS: Linux

Server Plugins
- Skript | 2.6.3 | Enabled: true
- IPWhitelist | 1.7 | Enabled: true
- PlaceholderAPI | 2.11.2 | Enabled: true
- ViaVersion | 4.3.1 | Enabled: true
- Ersatz | 1.0 | Enabled: true
- ViaBackwards | 4.3.0 | Enabled: true
- ProtocolLib | 4.8.0 | Enabled: true
- ViaRewind | 2.0.2 | Enabled: true
- LuckPerms | 5.4.30 | Enabled: true
- skRayFall | 1.9.27 | Enabled: true
- JFixLectern | 1.2 | Enabled: true
- 2FA | 1.6.2 | Enabled: true
- AuthMe | 5.6.0-SNAPSHOT-b2440 | Enabled: true
- LiteBans | 2.10.0 | Enabled: true

Server Jar, Versions and Information
- Spigot Build version: git-Purpur-1428 (MC: 1.17.1)
- Server Version: 1.17.1-R0.1-SNAPSHOT
- Version Instance: v1_17_1
- NMSVersion Instance: v1_17_R1
- Max Memory: 4294 MB
- Free Memory: 1674 MB
- Total Memory: 4294 MB

Communication Method & Proxies: 
- Using Bungeecord: true
- Is Proxy Loaded: true
- Communication Method in config: PROXY
- Communication Timeout in config: 30 ticks

Attach this file when creating an issue on GitHub: https://github.com/LielAmar/2FA/issues
You can also join our discord server and talk to us there: https://discord.com/invite/NzgBrqR

**Comment by LoneDevilX** [comment]
havign same issue here.

**Comment by DirtyConcept** [comment]
Should be fixed in version 1.7.0
